Repository bebrachel/EnrollEase_Backend, pull requests merged in 2023-12, with the labels that each got.

#14 Dev/add applicant service
  Dockerfile
  enrollease/.gitignore
  enrollease/.mvn/wrapper/maven-wrapper.jar
  enrollease/.mvn/wrapper/maven-wrapper.properties
  enrollease/compose.yaml
  enrollease/mvnw
  enrollease/mvnw.cmd
  enrollease/pom.xml
  enrollease/src/main/java/ru/nsu/enrollease/EnrolleaseApplication.java
  enrollease/src/main/java/ru/nsu/enrollease/GoogleAuthService.java
  enrollease/src/main/java/ru/nsu/enrollease/configuration/DatabaseConfig.java
  enrollease/src/main/java/ru/nsu/enrollease/configuration/WebSecurityConfig.java
  enrollease/src/main/java/ru/nsu/enrollease/controller/ApplicantController.java
  enrollease/src/main/java/ru/nsu/enrollease/controller/ColleagueController.java
  enrollease/src/main/java/ru/nsu/enrollease/dto/request/AllowOrGiveRolesRequest.java
  enrollease/src/main/java/ru/nsu/enrollease/dto/response/AllowOrGiveRolesResponse.java
  enrollease/src/main/java/ru/nsu/enrollease/dto/response/GetAllApplicantsResponse.java
  enrollease/src/main/java/ru/nsu/enrollease/dto/response/GetAllColleaguesResponse.java
  enrollease/src/main/java/ru/nsu/enrollease/model/Applicant.java
  enrollease/src/main/java/ru/nsu/enrollease/model/Colleague.java
  enrollease/src/main/java/ru/nsu/enrollease/repository/ApplicantRepository.java
  enrollease/src/main/java/ru/nsu/enrollease/repository/ColleagueRepository.java
  enrollease/src/main/java/ru/nsu/enrollease/service/ApplicantService.java
  enrollease/src/main/java/ru/nsu/enrollease/service/ColleagueService.java
  enrollease/src/main/resources/application.properties
  enrollease/src/test/java/ru/nsu/enrollease/EnrolleaseApplicationTests.java
  enrollease/src/test/java/ru/nsu/enrollease/TestEnrolleaseApplication.java
  scripts/excel_to_mongo/script.py
  scripts/excel_to_mongo/trigger.sh
  scripts/excel_to_mongo/xlsx/example_table_1.xlsx
  scripts/excel_to_mongo/xlsx/example_table_2.xlsx
  scripts/google_drive_creation/script.py
Labels: documentation, enhancement, instrument testing, new code

#3 Gmail API
  scripts/test_gmail/create_message.py
  scripts/test_gmail/filter_by_user.py
  scripts/test_gmail/get_thread_emails.py
Labels: new code

#20 Make scripts in one format
  scripts/excel_to_mongo/script.py
  scripts/google_drive_creation/script.py
  scripts/google_services/Google.py
  scripts/google_services/create_achievements_folder/script.py
  scripts/google_services/get_email_thread/script.py
  scripts/google_services/get_messages_by_user/script.py
  scripts/google_services/requirements.txt
  scripts/google_services/send_message/script.py
  scripts/test_gmail/create_message.py
Labels: refactor

#21 Login, roles, scripts
  scripts/googler/create_achievements_folder/script.py
Labels: new code
